version: 2.1
orbs:
  nx: nrwl/nx@1.5.1
  go: circleci/go@1.7.3
#  slack: circleci/slack@4.12.5
#  aws-cli: circleci/aws-cli@4.0.0
jobs:
  build_and_test: # this can be any name you choose
#    executor: node/default # use the default executor defined within the orb
    docker:
      - image: cimg/rust:1.70.0-node
    steps:
      - checkout
      - run:
          command: cargo test
          name: Run tests
      - run:
          command: cargo build --release
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths: .
#  test:
#    docker:
#      - image: cimg/rust:1.70.0
#      - image: cimg/node:lts-browsers
#    steps:
#      - checkout
##      - run: cargo clippy
#      - run: cargo test
##      - run: npm -v # fails todo
##      - run: pnpm nx run-many --target=build --max-parallel=2
#      - run: ls
#      - run: ls submodules/tauri-app
#      - run: pnpm nx run-many --target=build --max-parallel=3 --prod
workflows:
  build:
    jobs:
#      - agent:
#          matrix:
#            parameters:
#              ordinal: [1, 2]
#      - main
#      - test
      - build_and_test
#  build_test_deploy: # this can be any name you choose
#    jobs:
##      - build_and_test
#      - deploy:
##          requires:
##            - build_and_test # only deploy if the build_and_test job has completed
#          filters:
#            branches:
#              only: main # only deploy when on main

