version: 2.1
orbs:
  nx: nrwl/nx@1.6.2
jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: npm i
      - nx/set-shas
#      - run: npx nx format:check
#      - run: npm nx affected --target=build --parallel --max-parallel=3 --prod
#      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t test --parallel=3 --configuration=ci
#      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3
workflows:
  build:
    jobs:
      - main
